services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB13!
    volumes:
      - ./.container/mongo/data:/data/db
    ports:
      - '27017:27017'
