import { ApiProperty } from '@nestjs/swagger';

export interface IProblemDetail {
  // Any other arbitrary members specific to the problem occurrence
  [key: string]: any;

  correlationId: string;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string | string[];

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  instance: string;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the
   * origin server for this occurrence of the problem.
   */
  status: number;

  /**
   * The timestamp of the problem occurrence.
   */
  timestamp: string;

  /**
   * A short, human-readable summary of the problem type. It SHOULD NOT
   * change from occurrence to occurrence of the problem, except for
   * purposes of localization (e.g., using proactive content
   * negotiation; see [RFC7231], Section 3.4).
   */
  title: string;

  /**
   * A URI reference [RFC3986] that identifies the problem type. This
   * specification encourages the use of a dereferenceable URI that
   * provides human-readable documentation for the problem type (e.g.,
   * using HTML [W3C.REC-html5-20141028]).  When this member is not
   * present, its value is assumed to be "about:blank".
   */
  type: string;
}

export class HttpExceptionResponse implements IProblemDetail {
  @ApiProperty()
  correlationId: string;
  @ApiProperty()
  detail: string | string[];
  @ApiProperty()
  instance: string;
  @ApiProperty()
  status: number;
  @ApiProperty()
  timestamp: string;
  @ApiProperty()
  title: string;
  @ApiProperty()
  type: string;
}
